language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yestay90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yestay90/react-test npm run test -- --coverage

after_success:
  - docker build -t yestay90/multi-client ./client
  - docker build -t yestay90/multi-nginx ./nginx
  - docker build -t yestay90/multi-server ./server
  - docker build -t yestay90/multi-worker ./worker

  #  Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yestay90/multi-client
  - docker push yestay90/multi-nginx
  - docker push yestay90/multi-server
  - docker push yestay90/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-ap-south-1-154956132186"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
