language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yestay90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yestay90/react-test npm run test -- --coverage

after_success:
  - docker build -t yestay90/multi-client ./client
  - docker build -t yestay90/multi-nginx ./nginx
  - docker build -t yestay90/multi-server ./server
  - docker build -t yestay90/multi-worker ./worker
